# Converting the document to a .csv for ease. Splitting text to get orator.

In [1]:
import pandas as pd
script = pd.read_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\Python for DS- Project\conv.txt", header = None
                       ,delimiter = ':')
script.columns = ['Name', 'Speech']
script.to_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\Python for DS- Project\conv2.csv", 
                index = None)
script

             Name                                             Speech
0            WILL   I’ve never seen wildlings do a thing like thi...
1    WAYMAR ROYCE                             How close did you get?
2            WILL                            Close as any man would.
3           GARED                   We should head back to the wall.
4           ROYCE                          Do the dead frighten you?
..            ...                                                ...
106           NED                           Tell me about Jon Arryn.
107        ROBERT   One minute he was fine, and then … Burned rig...
108           NED                                       We both did.
109        ROBERT   He never had to teach you much, but me … You ...
110           NED                                               Aye.

[111 rows x 2 columns]

# List and number of unique characters

In [2]:
import numpy as np
name_1 = script["Name"].unique()
name_1 = np.array(name_1)
y = pd.Series(name_1)
print (y)

0              WILL
1      WAYMAR ROYCE
2             GARED
3             ROYCE
4               JON
5     SEPTA MORDANE
6             SANSA
7               NED
8              ROBB
9            CASSEL
10          CATELYN
11             BRAN
12            THEON
13           CERSEI
14            JAIME
15           ROBERT
16             ARYA
dtype: object

In [3]:
script["Name"].nunique()

17

In [4]:
script.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    111 non-null    object
 1   Speech  111 non-null    object
dtypes: object(2)
memory usage: 1.9+ KB

# Grouping and combined based on character

In [5]:
df = script.sort_values("Name")
df

             Name                                             Speech
97           ARYA   That’s Jaime Lannister. The queen’s twin brot...
95           ARYA                                              Arya.
92           ARYA                                   Where’s the Imp?
104          ARYA                                   Where’s the Imp?
41           BRAN                                   So he was lying?
..            ...                                                ...
1    WAYMAR ROYCE                             How close did you get?
10           WILL                                    They were here.
7            WILL   Whatever did it to them could do it to us. Th...
2            WILL                            Close as any man would.
0            WILL   I’ve never seen wildlings do a thing like thi...

[111 rows x 2 columns]

In [6]:
df['Speech'] = df.groupby(['Name'])['Speech'].transform(lambda x : ' '.join(x))
df = df.drop_duplicates()
df

              Name                                             Speech
97            ARYA   That’s Jaime Lannister. The queen’s twin brot...
41            BRAN   So he was lying?  What about you?  Please, fa...
53          CASSEL   They don’t belong down here.  The law is law,...
27         CATELYN   Ned. Ten is too young to see such things.  Do...
105         CERSEI   Where is our brother? Go find the little beas...
11           GARED   See where they went.  Our orders were to trac...
69           JAIME   If he told the king, both our heads would be ...
64             JON   I’m not a Stark. Get on.  You want to hold it...
40             NED   The White Walkers have been gone for thousand...
80            ROBB   Go on, Tommy, shave him good. He’s never met ...
88          ROBERT   Cat!  Take me to your crypt. I want to pay my...
4            ROYCE   Do the dead frighten you?  You don’t think he...
93           SANSA   Will you shut up?  Thank you.  Would you plea...
15   SEPTA MORDANE   Fine work, as always. Well done.  I love the ...
55           THEON   Right. Give it here.  I take orders from your...
1     WAYMAR ROYCE                             How close did you get?
10            WILL   They were here.  Whatever did it to them coul...

# Taking the speech, and getting unique words

In [7]:
def to_split(txt):
    return txt.split()

In [8]:
df['break'] = df['Speech'].apply(lambda x : to_split(x))
df

C:\Users\jason\AppData\Local\Temp/ipykernel_36900/3531909991.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['break'] = df['Speech'].apply(lambda x : to_split(x))

,Name,Speech,break
97,ARYA,That’s Jaime Lannister. The queen’s twin brot...,"[That’s, Jaime, Lannister., The, queen’s, twin..."
41,BRAN,"So he was lying? What about you? Please, fa...","[So, he, was, lying?, What, about, you?, Pleas..."
53,CASSEL,"They don’t belong down here. The law is law,...","[They, don’t, belong, down, here., The, law, i..."
27,CATELYN,Ned. Ten is too young to see such things. Do...,"[Ned., Ten, is, too, young, to, see, such, thi..."
105,CERSEI,Where is our brother? Go find the little beas...,"[Where, is, our, brother?, Go, find, the, litt..."
11,GARED,See where they went. Our orders were to trac...,"[See, where, they, went., Our, orders, were, t..."
69,JAIME,"If he told the king, both our heads would be ...","[If, he, told, the, king,, both, our, heads, w..."
64,JON,I’m not a Stark. Get on. You want to hold it...,"[I’m, not, a, Stark., Get, on., You, want, to,..."
40,NED,The White Walkers have been gone for thousand...,"[The, White, Walkers, have, been, gone, for, t..."
80,ROBB,"Go on, Tommy, shave him good. He’s never met ...","[Go, on,, Tommy,, shave, him, good., He’s, nev..."
88,ROBERT,Cat! Take me to your crypt. I want to pay my...,"[Cat!, Take, me, to, your, crypt., I, want, to..."
4,ROYCE,Do the dead frighten you? You don’t think he...,"[Do, the, dead, frighten, you?, You, don’t, th..."
93,SANSA,Will you shut up? Thank you. Would you plea...,"[Will, you, shut, up?, Thank, you., Would, you..."
15,SEPTA MORDANE,"Fine work, as always. Well done. I love the ...","[Fine, work,, as, always., Well, done., I, lov..."
55,THEON,Right. Give it here. I take orders from your...,"[Right., Give, it, here., I, take, orders, fro..."
1,WAYMAR ROYCE,How close did you get?,"[How, close, did, you, get?]"
10,WILL,They were here. Whatever did it to them coul...,"[They, were, here., Whatever, did, it, to, the..."

In [9]:
df['break_set'] = df['break'].apply(lambda x : set(x))

C:\Users\jason\AppData\Local\Temp/ipykernel_36900/650020888.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['break_set'] = df['break'].apply(lambda x : set(x))

In [10]:
 df.to_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\Python for DS- Project\conv2.csv", index = None)

In [11]:
df['break_set'] = df['break'].apply(lambda x : list(x))
df

C:\Users\jason\AppData\Local\Temp/ipykernel_36900/2459452361.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['break_set'] = df['break'].apply(lambda x : list(x))

,Name,Speech,break,break_set
97,ARYA,That’s Jaime Lannister. The queen’s twin brot...,"[That’s, Jaime, Lannister., The, queen’s, twin...","[That’s, Jaime, Lannister., The, queen’s, twin..."
41,BRAN,"So he was lying? What about you? Please, fa...","[So, he, was, lying?, What, about, you?, Pleas...","[So, he, was, lying?, What, about, you?, Pleas..."
53,CASSEL,"They don’t belong down here. The law is law,...","[They, don’t, belong, down, here., The, law, i...","[They, don’t, belong, down, here., The, law, i..."
27,CATELYN,Ned. Ten is too young to see such things. Do...,"[Ned., Ten, is, too, young, to, see, such, thi...","[Ned., Ten, is, too, young, to, see, such, thi..."
105,CERSEI,Where is our brother? Go find the little beas...,"[Where, is, our, brother?, Go, find, the, litt...","[Where, is, our, brother?, Go, find, the, litt..."
11,GARED,See where they went. Our orders were to trac...,"[See, where, they, went., Our, orders, were, t...","[See, where, they, went., Our, orders, were, t..."
69,JAIME,"If he told the king, both our heads would be ...","[If, he, told, the, king,, both, our, heads, w...","[If, he, told, the, king,, both, our, heads, w..."
64,JON,I’m not a Stark. Get on. You want to hold it...,"[I’m, not, a, Stark., Get, on., You, want, to,...","[I’m, not, a, Stark., Get, on., You, want, to,..."
40,NED,The White Walkers have been gone for thousand...,"[The, White, Walkers, have, been, gone, for, t...","[The, White, Walkers, have, been, gone, for, t..."
80,ROBB,"Go on, Tommy, shave him good. He’s never met ...","[Go, on,, Tommy,, shave, him, good., He’s, nev...","[Go, on,, Tommy,, shave, him, good., He’s, nev..."
88,ROBERT,Cat! Take me to your crypt. I want to pay my...,"[Cat!, Take, me, to, your, crypt., I, want, to...","[Cat!, Take, me, to, your, crypt., I, want, to..."
4,ROYCE,Do the dead frighten you? You don’t think he...,"[Do, the, dead, frighten, you?, You, don’t, th...","[Do, the, dead, frighten, you?, You, don’t, th..."
93,SANSA,Will you shut up? Thank you. Would you plea...,"[Will, you, shut, up?, Thank, you., Would, you...","[Will, you, shut, up?, Thank, you., Would, you..."
15,SEPTA MORDANE,"Fine work, as always. Well done. I love the ...","[Fine, work,, as, always., Well, done., I, lov...","[Fine, work,, as, always., Well, done., I, lov..."
55,THEON,Right. Give it here. I take orders from your...,"[Right., Give, it, here., I, take, orders, fro...","[Right., Give, it, here., I, take, orders, fro..."
1,WAYMAR ROYCE,How close did you get?,"[How, close, did, you, get?]","[How, close, did, you, get?]"
10,WILL,They were here. Whatever did it to them coul...,"[They, were, here., Whatever, did, it, to, the...","[They, were, here., Whatever, did, it, to, the..."

In [12]:
df_1 = df.drop(columns=["Speech","break"], axis=1)
df_1

              Name                                          break_set
97            ARYA  [That’s, Jaime, Lannister., The, queen’s, twin...
41            BRAN  [So, he, was, lying?, What, about, you?, Pleas...
53          CASSEL  [They, don’t, belong, down, here., The, law, i...
27         CATELYN  [Ned., Ten, is, too, young, to, see, such, thi...
105         CERSEI  [Where, is, our, brother?, Go, find, the, litt...
11           GARED  [See, where, they, went., Our, orders, were, t...
69           JAIME  [If, he, told, the, king,, both, our, heads, w...
64             JON  [I’m, not, a, Stark., Get, on., You, want, to,...
40             NED  [The, White, Walkers, have, been, gone, for, t...
80            ROBB  [Go, on,, Tommy,, shave, him, good., He’s, nev...
88          ROBERT  [Cat!, Take, me, to, your, crypt., I, want, to...
4            ROYCE  [Do, the, dead, frighten, you?, You, don’t, th...
93           SANSA  [Will, you, shut, up?, Thank, you., Would, you...
15   SEPTA MORDANE  [Fine, work,, as, always., Well, done., I, lov...
55           THEON  [Right., Give, it, here., I, take, orders, fro...
1     WAYMAR ROYCE                       [How, close, did, you, get?]
10            WILL  [They, were, here., Whatever, did, it, to, the...

In [13]:
df_1['break_set'] = df_1['break_set'].astype("string")
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17 entries, 97 to 10
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       17 non-null     object
 1   break_set  17 non-null     string
dtypes: object(1), string(1)
memory usage: 408.0+ bytes

In [14]:
df_1 = df.drop(columns=["break_set","Speech","break"], axis=1)
df_2 = pd.DataFrame(df['break_set'].values.tolist())
df_1 = df_1.reset_index(drop=True)
df_2 = df_2.reset_index(drop=True)
clean = pd.concat([df_1, df_2], axis=1)
final = clean
final.to_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\Python for DS- Project\speaker.csv")

In [15]:
final

,Name,0,1,2,3,4,5,6,7,8,...,198,199,200,201,202,203,204,205,206,207
0,ARYA,That’s,Jaime,Lannister.,The,queen’s,twin,brother.,Arya.,Where’s,...,None,None,None,None,None,None,None,None,None,None
1,BRAN,So,he,was,lying?,What,about,you?,"Please,",father!,...,None,None,None,None,None,None,None,None,None,None
2,CASSEL,They,don’t,belong,down,here.,The,law,is,"law,",...,None,None,None,None,None,None,None,None,None,None
3,CATELYN,Ned.,Ten,is,too,young,to,see,such,things.,...,None,None,None,None,None,None,None,None,None,None
4,CERSEI,Where,is,our,brother?,Go,find,the,little,beast.,...,None,None,None,None,None,None,None,None,None,None
5,GARED,See,where,they,went.,Our,orders,were,to,track,...,None,None,None,None,None,None,None,None,None,None
6,JAIME,If,he,told,the,"king,",both,our,heads,would,...,None,None,None,None,None,None,None,None,None,None
7,JON,I’m,not,a,Stark.,Get,on.,You,want,to,...,None,None,None,None,None,None,None,None,None,None
8,NED,The,White,Walkers,have,been,gone,for,thousands,of,...,you,understand,why,I,had,to,kill,him?,My,queen.
9,ROBB,Go,"on,","Tommy,",shave,him,good.,He’s,never,met,...,None,None,None,None,None,None,None,None,None,None
10,ROBERT,Cat!,Take,me,to,your,crypt.,I,want,to,...,None,None,None,None,None,None,None,None,None,None
11,ROYCE,Do,the,dead,frighten,you?,You,don’t,think,he’ll,...,None,None,None,None,None,None,None,None,None,None
12,SANSA,Will,you,shut,up?,Thank,you.,Would,you,please,...,None,None,None,None,None,None,None,None,None,None
13,SEPTA MORDANE,Fine,"work,",as,always.,Well,done.,I,love,the,...,None,None,None,None,None,None,None,None,None,None
14,THEON,Right.,Give,it,here.,I,take,orders,from,your,...,None,None,None,None,None,None,None,None,None,None
15,WAYMAR ROYCE,How,close,did,you,get?,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
16,WILL,They,were,here.,Whatever,did,it,to,them,could,...,None,None,None,None,None,None,None,None,None,None

In [19]:
import csv
filename = r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\Python for DS- Project\speaker.csv"

with open(filename, 'r') as csvfile:
    reader = csv.reader(csvfile)
    i = 1
    for row in reader:
        with open("Name"+str(i)+".txt", 'w') as f: #filename to be name of person 9iterating through column 1
            f.write(str(row)) # break after word (cell) \n
        i+=1

FileNotFoundError: [Errno 2] No such file or directory: '0              ARYA\n1              BRAN\n2            CASSEL\n3           CATELYN\n4            CERSEI\n5             GARED\n6             JAIME\n7               JON\n8               NED\n9              ROBB\n10           ROBERT\n11            ROYCE\n12            SANSA\n13    SEPTA MORDANE\n14            THEON\n15     WAYMAR ROYCE\n16             WILL\nName: Name, dtype: object1.txt'